# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$13$ZuGeePen2PlcouNCRAC.POBguxNSxqMGHtdWK0d5tl1RcQ.4CwjjW
                        roles: 'ROLE_ADMIN'
#        our_db_provider:
#            entity:
#                class: AppBundle:User
#                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            http_basic: ~
#            provider: our_db_provider

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: ROLE_ADMIN }

#    encoders:
#        AppBundle\Entity\User:
#            algorithm: bcrypt
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12
